### ISSUE TITLE
Cannot run keycloak with it 21.0.1

### ISSUE THREAD

**Issue by MichalNemec** [softwarefactory-project/keycloak-event-listener-mqtt#10]
ive done mvn clean package
then moved .jar to providers, did volume hookup to quay.io and result is:
```
ERROR: Failed to run 'build' command.
keycloak-round-2-keycloak-1     | ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
keycloak-round-2-keycloak-1     | 	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.util.ServiceConfigurationError: org.keycloak.events.EventListenerProviderFactory: org.softwarefactory.keycloak.providers.events.mqtt.MQTTEventListenerProviderFactory Unable to get public no-arg constructor
```

how to solve this?

**Comment by mhuin** [comment]
what version of java are you using to build the package?
Have you tried using the latest package that was released instead of building it manually?

**Comment by MichalNemec** [comment]
java --version
java 18.0.1.1 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

i want to build it so i have "dev" code so i can create my own variations afterwards, so that the setup is correct, its hard to do and find custom extensions which would work.. entire day trying and no extension loaded, until this one

**Comment by MichalNemec** [comment]
> Have you tried using the latest package that was released instead of building it manually?

Yes and its the same issue:
```
ERROR: Build failure: Build failed due to errors
keycloak             | 	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.util.ServiceConfigurationError: org.keycloak.events.EventListenerProviderFactory: org.softwarefactory.keycloak.providers.events.mqtt.MQTTEventListenerProviderFactory Unable to get public no-arg constructor
keycloak             | 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
keycloak             | 	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
keycloak             | 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
keycloak             | 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
keycloak             | 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
keycloak             | 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
keycloak             | 	at org.keycloak.provider.DefaultProviderLoader.load(DefaultProviderLoader.java:60)
keycloak             | 	at org.keycloak.provider.ProviderManager.load(ProviderManager.java:94)
keycloak             | 	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadFactories(KeycloakProcessor.java:663)
keycloak             | 	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureKeycloakSessionFactory(KeycloakProcessor.java:365)
keycloak             | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak             | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
keycloak             | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak             | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
keycloak             | 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
keycloak             | 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
keycloak             | 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
keycloak             | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
keycloak             | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
keycloak             | 	at java.base/java.lang.Thread.run(Thread.java:833)
keycloak             | 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
keycloak             | Caused by: java.lang.NoClassDefFoundError: org/eclipse/paho/client/mqttv3/MqttSecurityException
keycloak             | 	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
keycloak             | 	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
keycloak             | 	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
keycloak             | 	at java.base/java.lang.Class.getConstructor(Class.java:2271)
keycloak             | 	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)
keycloak             | 	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)
keycloak             | 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
keycloak             | 	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
keycloak             | 	... 19 more
keycloak             | Caused by: java.lang.ClassNotFoundException: org.eclipse.paho.client.mqttv3.MqttSecurityException
keycloak             | 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:507)
keycloak             | 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
keycloak             | 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:505)
keycloak             | 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
keycloak             | 	... 27 more

```

**Comment by MichalNemec** [comment]
suddenly it started to work
